services:
  linkstack:
    hostname: linkstack
    image: linkstackorg/linkstack:latest
    environment:
      TZ: "${TZ}"
      SERVER_ADMIN: "${SERVER_ADMIN}"
      HTTP_SERVER_NAME: "${HTTP_SERVER_NAME}"
      HTTPS_SERVER_NAME: "${HTTPS_SERVER_NAME}"
      LOG_LEVEL: info
      PHP_MEMORY_LIMIT: 256M
      UPLOAD_MAX_FILESIZE: 8M
    volumes:
      - ./htdocs:/var/www/html
    ports:
      - "8080:80"
      - "8081:443"
    restart: unless-stopped
    user: apache:apache
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    ports:
      - "3306:3306"
